name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./...
      - name: Install otel-cli for tests
        uses: jaxxstorm/action-install-gh-release@release/v1-alpha
        with:
          repo: equinix-labs/otel-cli
      - name: Test
        run: go test -v ./...
