name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install otel-cli for tests
        uses: engineerd/configurator@v0.0.8
        with:
          name: "otel-cli"
          pathInArchive: /otel-cli
          fromGitHubReleases: "true"
          repo: equinix-labs/otel-cli
          version: "^v0.0.5"
          urlTemplate: "https://github.com/equinix-labs/otel-cli/releases/download/{{ version }}/otel-cli-{{ version }}-Linux-x86_64.tar.gz"
          token: ${{ secrets.GTIHUB_TOKEN }}
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
